[package]
name = "asset"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
utils = { path = "../../utils/" }
surrealdb = { version = "1.5.0", default-features = false }
rkyv = { version = "0.7.44", features = ["strict"] }
